import React, { useState } from 'react';

function FormWizard({ form, ui, lang, onBack }) {
  const [currentStep, setCurrentStep] = useState(0);
  const [answers, setAnswers] = useState({});
  const [errors, setErrors] = useState({});
  const [completed, setCompleted] = useState(false);
  const [docChecked, setDocChecked] = useState({});

  // Show one field per step, then documents, then submission
  const totalSteps = form.fields.length + 2; // fields + docs + submit
  const isDocStep = currentStep === form.fields.length;
  const isSubmitStep = currentStep === form.fields.length + 1;
  const currentField = form.fields[currentStep];

  const progress = ((currentStep + 1) / totalSteps) * 100;

  const handleAnswer = (fieldId, value) => {
    setAnswers(prev => ({ ...prev, [fieldId]: value }));
    setErrors(prev => ({ ...prev, [fieldId]: null }));
  };

  const validateCurrent = () => {
    if (isDocStep || isSubmitStep) return true;
    if (currentField.required && (!answers[currentField.id] || answers[currentField.id].trim() === '')) {
      setErrors(prev => ({ ...prev, [currentField.id]: ui.fieldRequired }));
      return false;
    }
    return true;
  };

  const next = () => {
    if (!validateCurrent()) return;
    if (isSubmitStep) {
      setCompleted(true);
      return;
    }
    setCurrentStep(prev => prev + 1);
  };

  const prev = () => {
    if (currentStep > 0) setCurrentStep(prev => prev - 1);
  };

  const handleDownload = () => {
    const content = [
      form.name,
      '='.repeat(40),
      '',
      ...form.fields.map(f => `${f.label}: ${answers[f.id] || '-'}`),
      '',
      '='.repeat(40),
      `Generated by FormFriend - ${new Date().toLocaleDateString()}`
    ].join('\n');

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${form.id}_filled.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  if (completed) {
    return (
      <div>
        <button className="back-btn" onClick={onBack}>
          &larr; {ui.forms}
        </button>
        <div className="wizard">
          <div className="completion">
            <h2>{ui.formCompleted}</h2>
            <p>{ui.downloadReady}</p>

            <div style={{ marginBottom: '1.5rem', textAlign: 'left' }}>
              <h3 style={{ marginBottom: '0.75rem' }}>
                {lang === 'de' ? 'Ihre Angaben:' : 'Your answers:'}
              </h3>
              {form.fields.map(f => (
                <div key={f.id} style={{ padding: '0.5rem 0', borderBottom: '1px solid #e2e8f0' }}>
                  <strong>{f.label}:</strong> {answers[f.id] || '-'}
                </div>
              ))}
            </div>

            <button className="btn btn-success btn-large" onClick={handleDownload}>
              {ui.download}
            </button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div>
      <button className="back-btn" onClick={onBack}>
        &larr; {ui.forms}
      </button>
      <div className="wizard">
        <div className="wizard-header">
          <h2>{form.name}</h2>
          <div className="wizard-progress">
            <span>{ui.step} {currentStep + 1} {ui.of} {totalSteps}</span>
            <div className="progress-bar">
              <div className="progress-fill" style={{ width: `${progress}%` }} />
            </div>
          </div>
        </div>

        <div className="wizard-body">
          {/* Field step */}
          {!isDocStep && !isSubmitStep && currentField && (
            <div className="field-group">
              <label className="field-label">{currentField.label}</label>
              <div className="field-explanation">{currentField.explanation}</div>

              {currentField.type === 'select' ? (
                <select
                  className="field-select"
                  value={answers[currentField.id] || ''}
                  onChange={e => handleAnswer(currentField.id, e.target.value)}
                >
                  <option value="">--</option>
                  {currentField.options.map(opt => (
                    <option key={opt.value} value={opt.value}>
                      {opt.label}
                    </option>
                  ))}
                </select>
              ) : (
                <input
                  className="field-input"
                  type={currentField.type === 'date' ? 'date' : 'text'}
                  value={answers[currentField.id] || ''}
                  onChange={e => handleAnswer(currentField.id, e.target.value)}
                  autoFocus
                />
              )}

              {errors[currentField.id] && (
                <div className="field-error">{errors[currentField.id]}</div>
              )}
            </div>
          )}

          {/* Documents checklist step */}
          {isDocStep && (
            <div className="documents-section">
              <h3>{ui.documentChecklist}</h3>
              <p style={{ color: '#64748b', marginBottom: '1rem' }}>
                {lang === 'de' ? 'Haben Sie diese Dokumente bereit?' : lang === 'en' ? 'Do you have these documents ready?' : lang === 'ar' ? 'هل لديك هذه المستندات جاهزة؟' : lang === 'tr' ? 'Bu belgeleri hazırladınız mı?' : lang === 'uk' ? 'Чи є у вас ці документи?' : lang === 'fr' ? 'Avez-vous ces documents prêts ?' : 'آیا این مدارک را آماده دارید؟'}
              </p>
              <ul className="doc-list">
                {form.requiredDocuments.map((doc, i) => (
                  <li key={i} className="doc-item">
                    <input
                      type="checkbox"
                      className="doc-checkbox"
                      checked={docChecked[i] || false}
                      onChange={e => setDocChecked(prev => ({ ...prev, [i]: e.target.checked }))}
                    />
                    <span>{doc}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}

          {/* Submission info step */}
          {isSubmitStep && (
            <div>
              <div className="submission-info">
                <h3>{ui.submissionInfo}</h3>
                <p>{form.submissionInfo}</p>
              </div>

              <div style={{ marginTop: '1.5rem' }}>
                <h3 style={{ marginBottom: '0.75rem' }}>
                  {lang === 'de' ? 'Zusammenfassung Ihrer Angaben:' : 'Summary of your answers:'}
                </h3>
                {form.fields.map(f => (
                  <div key={f.id} style={{ padding: '0.4rem 0', color: '#475569' }}>
                    <strong>{f.label}:</strong> {answers[f.id] || '-'}
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>

        <div className="wizard-footer">
          <button
            className="btn btn-secondary"
            onClick={prev}
            disabled={currentStep === 0}
          >
            {ui.previousStep}
          </button>
          <button className="btn btn-primary" onClick={next}>
            {isSubmitStep ? ui.submit : ui.nextStep}
          </button>
        </div>
      </div>
    </div>
  );
}

export default FormWizard;
